export const data = [
    {
        englishName:'platform',
        persianName:'سکو',
        year:'2019',
        country:'es',
        duration:'01:34:33',
        owner:'A',
        status:'active',
    },
    {
        englishName:'God Father',
        persianName:'پدر خوانده',
        year:'1994',
        country:'us',
        duration:'02:40:00',
        owner:'B',
        status:'active',
    },
    {
        englishName:'Seperation',
        persianName:'جدایی',
        year:'2018',
        country:'ir',
        duration:'01:50:33',
        owner:'C',
        status:'active',
    },
    {
        englishName:'Fight Club',
        persianName:'باشگاه مشت زنی',
        year:'2001',
        country:'us',
        duration:'02:20:33',
        owner:'A',
        status:'active',
    },
    {
        englishName:'Inception',
        persianName:'تلقین',
        year:'2014',
        country:'us',
        duration:'02:30:33',
        owner:'C',
        status:'active',
    },
    {
        englishName:'Revenent',
        persianName:'از گور بازگشته',
        year:'2016',
        country:'us',
        duration:'01:50:33',
        owner:'C',
        status:'active',
    },
    {
        englishName:'Room',
        persianName:'اتاق',
        year:'2016',
        country:'us',
        duration:'01:50:33',
        owner:'C',
        status:'active',
    },
    {
        englishName:'Old',
        persianName:'پیر',
        year:'2021',
        country:'us',
        duration:'01:20:33',
        owner:'C',
        status:'active',
    },
    {
        englishName:'Split',
        persianName:'شکافته',
        year:'2015',
        country:'us',
        duration:'01:50:33',
        owner:'C',
        status:'active',
    },
    {
        englishName:'Glass',
        persianName:'شیشه',
        year:'2019',
        country:'us',
        duration:'02:10:05',
        owner:'C',
        status:'active',
    },
    {
        englishName:'The SalESman',
        persianName:'فروشنده',
        year:'2016',
        country:'ir',
        duration:'02:05:00',
        owner:'C',
        status:'active',
    },
    {
        englishName:'Marriage Story',
        persianName:'داستان ازدواج',
        year:'2019',
        country:'us',
        duration:'02:17:00',
        owner:'C',
        status:'active',
    },
    {
        englishName:'The Lighthouse',
        persianName:'فانوس دریایی',
        year:'2019',
        country:'us',
        duration:'02:17:00',
        owner:'C',
        status:'active',
    },
    {
        englishName:'Midsommer',
        persianName:'بین تابستانی',
        year:'2019',
        country:'us',
        duration:'02:20:00',
        owner:'C',
        status:'active',
    },
];